### ISSUE TITLE
Game is crashing on startup when i add this mod to my Modpack (1.12)

### ISSUE THREAD

**Issue by bastie2606** [Furgl/Stupid-Things#11] opened 2018-02-11 23:05 UTC
Hey

so I was just making my modpack and I wanted to add this mod too the modpack
but when I started up the game it crashed I can't say if it is the fault of this mod, if not then I am sorry that I wasted your time
here is the report:
https://pastebin.com/sBTec2zK

**Comment by Furgl** [comment] 2018-02-13 00:02
The issue was caused by this mod, thank you for reporting it! It's fixed in v1.1.5: [https://minecraft.curseforge.com/projects/stupid-things/files](https://minecraft.curseforge.com/projects/stupid-things/files)

**Closed as completed by Furgl** 2018-02-13 00:02 UTC
